spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: http://localhost:29092
    consumer:
      auto-offset-reset: earliest
      group-id: kafka-consumer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-db
  banner:
    location: banner.txt
server:
  port: 4040